spring:
  application:
    name: insurance-reports-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/test_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    #show-sql: true
  batch:
    job:
      enabled: false